"""Load the frozen model and score candidate actions with it.

Training writes four artifacts; this is the only thing that reads them back. Everything
downstream — the policy, the agent's ``assess_recoverability`` tool, the API — goes
through here, so there is exactly one place where a probability enters the system and
exactly one definition of the column order it was produced from.

**Why the calibrator is the artifact that gets loaded.** ``calibrator_v1.joblib`` is a
``CalibratedClassifierCV`` wrapping a ``FrozenEstimator`` around the fitted booster, so
the pickle contains the booster too. The scorer therefore needs one file to answer a
question, and the answer is the calibrated probability rather than the raw one — the
policy multiplies probabilities by rupees, and an uncalibrated score is not a number you
may multiply by money.

``model_v1.json`` is loaded anyway, and not for redundancy. A pickle is opaque: nothing
about it tells a reader which trees are inside. The JSON booster is the auditable copy,
and :func:`verify_artifacts` scores both and asserts they agree, so the readable artifact
is demonstrably the model that is running rather than a file that merely sits next to it.

**On the pickle, since joblib deserialisation executes code.** The only file this module
unpickles is one this repository produced, committed under ``ml/artifacts/`` and
regenerated by ``python -m ml``; nothing here loads a calibrator from a request, an
upload, or any other input a user controls, and the loader is not exposed through the
API. If that ever changes — a model shipped from outside the repo — the correct move is
to drop the pickle entirely and rebuild the calibrator from ``model_v1.json`` plus its
coefficients, not to add a check to this file.

The pickle is also the more fragile of the two artifacts across upgrades — loading it
already emits a NumPy 2.5 deprecation warning from inside joblib — which is the second
reason the JSON booster is kept and checked rather than merely archived.

**Why the column order is read from disk and not rebuilt.** ``ml.features`` could produce
the names, and one day it will produce them in a different order — a column inserted, a
one-hot renamed — and a matrix assembled in that new order would score cleanly against
the old booster and be silently, plausibly wrong. The names travel with the model, and a
row that does not match them exactly is refused.
"""

from __future__ import annotations

import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

import joblib
import numpy as np
import xgboost as xgb
from sklearn.calibration import CalibratedClassifierCV

from ml.train import ARTIFACTS


class ArtifactError(RuntimeError):
    """A model artifact is missing, unreadable, or disagrees with its siblings."""


@dataclass(frozen=True, slots=True)
class Scorer:
    """The frozen model, behind the narrowest interface the policy can use."""

    calibrator: CalibratedClassifierCV
    #: Which of the three calibrators won on the calibration split. Carried so the
    #: audit row can name it: "sigmoid" is a fact about this run, not about the code.
    method: str
    feature_names: tuple[str, ...]
    best_iteration: int

    def matrix(self, rows: Sequence[Mapping[str, float]]) -> np.ndarray:
        """Assemble feature dictionaries into the model's own column order.

        Refuses a row whose keys are not exactly the frozen names. Missing is the
        obvious error; extra is the interesting one, because a caller that has built a
        feature the model was never trained on has built the wrong row, and dropping it
        quietly would let the two definitions drift apart for as long as nobody looked.
        """
        expected = set(self.feature_names)
        out = np.empty((len(rows), len(self.feature_names)), dtype=np.float32)
        for index, row in enumerate(rows):
            keys = set(row)
            if keys != expected:
                missing = sorted(expected - keys)
                extra = sorted(keys - expected)
                raise ArtifactError(
                    f"row {index} does not match the frozen feature set: "
                    f"missing {missing}, unexpected {extra}"
                )
            out[index] = [row[name] for name in self.feature_names]
        return out

    def score(self, rows: Sequence[Mapping[str, float]]) -> np.ndarray:
        """Calibrated P(captured) for each candidate row."""
        if not rows:
            return np.empty(0, dtype=np.float64)
        return self.calibrator.predict_proba(self.matrix(rows))[:, 1]

    def score_one(self, row: Mapping[str, float]) -> float:
        """Calibrated P(captured) for a single candidate."""
        return float(self.score([row])[0])


def _read_meta(directory: Path) -> dict:
    path = directory / "model_v1.meta.json"
    if not path.exists():
        raise ArtifactError(f"{path} is missing — run `python -m ml` to train and freeze the model")
    return json.loads(path.read_text())


@lru_cache(maxsize=4)
def load_scorer(directory: Path = ARTIFACTS) -> Scorer:
    """Load the frozen model. Cached: the policy asks for it once per candidate.

    The cache is keyed on the directory, so a test pointing at a temporary artifacts
    directory does not collide with the committed one.
    """
    meta = _read_meta(directory)
    path = directory / "calibrator_v1.joblib"
    if not path.exists():
        raise ArtifactError(f"{path} is missing — run `python -m ml` to train and freeze the model")
    bundle = joblib.load(path)
    calibrator: CalibratedClassifierCV = bundle["model"]

    names = tuple(meta["feature_names"])
    width = getattr(calibrator, "n_features_in_", len(names))
    if width != len(names):
        raise ArtifactError(
            f"the calibrator expects {width} features but the metadata names "
            f"{len(names)}; the artifacts in {directory} are from different runs"
        )
    return Scorer(
        calibrator=calibrator,
        method=str(bundle["method"]),
        feature_names=names,
        best_iteration=int(meta["best_iteration"]),
    )


def load_booster(directory: Path = ARTIFACTS) -> xgb.Booster:
    """The readable copy of the model, loaded from JSON rather than from a pickle."""
    path = directory / "model_v1.json"
    if not path.exists():
        raise ArtifactError(f"{path} is missing — run `python -m ml`")
    booster = xgb.Booster()
    booster.load_model(str(path))
    return booster


def verify_artifacts(X: np.ndarray, *, directory: Path = ARTIFACTS) -> float:
    """Assert the JSON booster and the pickled one are the same model.

    Returns the largest absolute disagreement in uncalibrated probability across ``X``,
    which is the number a test asserts on. Both are scored over the same iteration range
    — the pickle stops at ``best_iteration`` because early stopping told it to, and a
    raw booster asked for all of its trees would answer a different question and look
    like a mismatch that isn't one.
    """
    scorer = load_scorer(directory)
    booster = load_booster(directory)
    iteration_range = (0, scorer.best_iteration + 1)

    from_json = booster.predict(xgb.DMatrix(X), iteration_range=iteration_range)
    inner = scorer.calibrator.estimator.estimator  # FrozenEstimator -> XGBClassifier
    from_pickle = inner.predict_proba(X)[:, 1]
    return float(np.max(np.abs(from_json - from_pickle)))
