"""NPCI non-peak execution window.

Source: NPCI circular OC-215-A, effective 1 August 2025. Mandate execution is
permitted only outside peak hours. Peak, in IST: 10:00-13:00 and 17:00-21:30.

Two decisions are fixed here and referenced everywhere else:

* **Peak windows are half-open, ``[start, end)``.** 10:00:00 is peak, 13:00:00 is not.
  This is the reading under which adjacent windows tile without overlap or gap.
* **A mistimed proposal is redirected, never dropped.** An action proposed at 11:00 is
  legal; it is merely early. Discarding it forfeits a recovery for no compliance gain,
  so the guardrail's answer is ``REDIRECT_TO_WINDOW`` with a slot attached.

Every function here is pure and takes an explicit timestamp. Nothing reads the clock,
so the whole rule is reproducible in a test and in a replayed audit trail alike.
"""

from __future__ import annotations

from datetime import datetime, time, timedelta
from zoneinfo import ZoneInfo

IST = ZoneInfo("Asia/Kolkata")

#: Peak windows in IST, half-open and in ascending order.
PEAK_WINDOWS: tuple[tuple[time, time], ...] = (
    (time(10, 0), time(13, 0)),
    (time(17, 0), time(21, 30)),
)

#: Candidate execution slots, all inside non-peak bands.
#:
#: A discrete anchor grid rather than a continuous search, for two reasons: the
#: candidate set the model scores stays finite and enumerable, and every slot the
#: agent proposes is one a human can recognise as a deliberate choice. 02:00 is when
#: bank batch settlement lands; 07:00 and 09:00 sit before the morning peak; 22:00 and
#: 23:30 catch the post-peak evening. The policy layer decides which anchor is worth
#: spending an attempt on -- payday proximity, root cause, remaining budget. This
#: module only guarantees that all of them are legal.
SLOT_ANCHORS: tuple[time, ...] = (
    time(2, 0),
    time(7, 0),
    time(9, 0),
    time(13, 30),
    time(15, 30),
    time(22, 0),
    time(23, 30),
)


def _to_ist(moment: datetime) -> datetime:
    """Convert to IST, refusing to guess at a naive timestamp.

    A naive datetime silently interpreted as local time is how an execution that is
    legal in one deployment becomes a violation in another. Refuse instead.
    """
    if moment.tzinfo is None or moment.tzinfo.utcoffset(moment) is None:
        raise ValueError(
            "non_peak_window requires a timezone-aware datetime; "
            "a naive timestamp would have to be guessed at, and this rule is IST."
        )
    return moment.astimezone(IST)


def is_non_peak(moment: datetime) -> bool:
    """True when NPCI permits mandate execution at this instant."""
    clock = _to_ist(moment).timetz().replace(tzinfo=None)
    return not any(start <= clock < end for start, end in PEAK_WINDOWS)


def next_slots(after: datetime, n: int = 3) -> list[datetime]:
    """The next ``n`` legal execution slots strictly after ``after``.

    This is what the guardrail hands the model: the candidate set is generated by the
    compliance layer, so the model is never in a position to rank an illegal option.
    Crosses midnight when the day's anchors are exhausted -- without that, a failure
    at 23:50 would silently have no candidates at all.
    """
    if n < 1:
        raise ValueError(f"next_slots needs at least one slot; asked for {n}")

    cursor = _to_ist(after)
    day = cursor.date()
    slots: list[datetime] = []

    # One extra day of headroom beyond the worst case, so an anchor list that someone
    # later trims cannot turn into an unbounded loop.
    for offset in range(n + 2):
        current_day = day + timedelta(days=offset)
        for anchor in SLOT_ANCHORS:
            slot = datetime.combine(current_day, anchor, tzinfo=IST)
            if slot > cursor and is_non_peak(slot):
                slots.append(slot)
                if len(slots) == n:
                    return slots

    # Unreachable while SLOT_ANCHORS is non-empty and legal, which
    # test_slot_anchors_are_themselves_legal enforces.
    raise RuntimeError(f"could not find {n} legal slots after {after.isoformat()}")


def time_to_next_transition(moment: datetime) -> timedelta:
    """Time until the peak/non-peak state next flips.

    Drives the dashboard's live countdown, which is the cheapest way to make the rule
    legible to someone watching a demo: the window is visibly a clock, not a claim.
    Always strictly positive -- a boundary instant counts to the *next* flip, so the
    countdown never renders as stuck.
    """
    cursor = _to_ist(moment)
    clock = cursor.timetz().replace(tzinfo=None)

    transitions = sorted(edge for window in PEAK_WINDOWS for edge in window)
    for edge in transitions:
        if edge > clock:
            return datetime.combine(cursor.date(), edge, tzinfo=IST) - cursor

    tomorrow = cursor.date() + timedelta(days=1)
    return datetime.combine(tomorrow, transitions[0], tzinfo=IST) - cursor
