"""What the policy is allowed to decide, and what it is structurally unable to decide.

The tests are grouped by which claim they defend:

1. **The guardrail bounds the choice.** Every claim of the form "the model never argues
   with the law" has to be a property of the code, not of the prompt. These tests give
   the policy states in which the legal answer is forced and check it produced that
   answer — including the case where the forced answer costs it money.
2. **Doing nothing is a real option.** A recovery policy that always recovers is a
   policy with no cost model. Write-off has to win somewhere, and the somewhere has to
   be the economically correct place.
3. **The lookahead is a lookahead.** It is easy to write a backward induction that
   silently degenerates into a greedy argmax. These check the continuation value is
   actually in the number.
4. **The nudge belief is the policy's own.** Its shape is tested here; its size is a
   stated assumption reported across a range in ``docs/EVALUATION.md``.

Synthetic rows throughout, rather than the frozen dataset. The behaviours below are about
the decision rule, and a fixture built by hand can be put in states the generator does not
happen to produce — an exhausted attempt budget, a revoked mandate, a ₹40,000 debit.
"""

from __future__ import annotations

from dataclasses import replace
from datetime import date, datetime, timedelta

import pytest

from compliance.guardrail import ActionKind
from compliance.non_peak_window import IST, is_non_peak
from compliance.result import Verdict
from compliance.root_cause import RootCause
from core.money import paise
from ml import policy
from ml.features import BankMethodRates, PriorState
from ml.policy import DEFAULT_POLICY, InvoiceState, decide
from ml.scorer import Scorer, load_scorer
from ml.train import ARTIFACTS
from sim.generate import CustomerRow, InvoiceRow, SubscriptionRow

#: 02:00 IST — legal under OC-215-A, and the first decision point in every test below.
NOW = datetime(2026, 9, 14, 2, 0, tzinfo=IST)

CUSTOMER = CustomerRow(
    customer_id="cust_0001",
    customer_hash="a1b2c3d4e5f6",
    signup_date=date(2025, 6, 1),
    consent_status="active",
    consent_updated_at=datetime(2025, 6, 1, 9, 0, tzinfo=IST),
    salary_day=1,
    monthly_headroom_paise=paise(12_000),
)
SUBSCRIPTION = SubscriptionRow(
    subscription_id="sub_0001",
    customer_id="cust_0001",
    method="upi_autopay",
    bank="HDFC",
    mcc_category="saas",
    amount_paise=paise(1_499),
    status="active",
    mandate_start=date(2025, 6, 1),
    paid_count=3,
    remaining_count=9,
    cohort="test",
)
INVOICE = InvoiceRow(
    invoice_id="inv_0001",
    subscription_id="sub_0001",
    cycle_number=4,
    amount_paise=paise(1_499),
    charge_at=NOW - timedelta(hours=2),
    notice_sent_at=NOW - timedelta(days=2),
    status="failed",
)
PRIOR = PriorState(
    prior_root_cause="TD",
    prior_failures_this_invoice=1,
    last_attempt_at=NOW - timedelta(hours=2),
    last_success_at=NOW - timedelta(days=30),
    lifetime_attempts=4,
    lifetime_failures=1,
)


@pytest.fixture(scope="module")
def scorer() -> Scorer:
    return load_scorer(ARTIFACTS)


@pytest.fixture(scope="module")
def rates() -> BankMethodRates:
    """A flat prior. The point of these tests is the decision rule, not the rate table."""
    return BankMethodRates(rates={}, fallback=0.12)


def state(**overrides) -> InvoiceState:
    base = {
        "subscription": SUBSCRIPTION,
        "customer": CUSTOMER,
        "invoice": INVOICE,
        "attempts_used": 1,
        "root_cause": RootCause.TD,
        "prior": PRIOR,
        "now": NOW,
    }
    return InvoiceState(**(base | overrides))


# ------------------------------------------------- the guardrail bounds the choice


def test_every_slot_the_policy_proposes_is_legal(scorer, rates) -> None:
    """The candidate set is generated by the compliance layer, so an illegal slot never
    acquires a value that would then have to be argued down."""
    plan = decide(state(), scorer=scorer, rates=rates)
    retries = [c for c in plan.candidates if c.kind is ActionKind.RETRY]
    assert retries, "a fresh invoice with one attempt used must have legal retries"
    assert all(is_non_peak(candidate.execute_at) for candidate in retries)


def test_the_chosen_action_is_always_one_the_guardrail_approved(scorer, rates) -> None:
    plan = decide(state(), scorer=scorer, rates=rates)
    assert plan.chosen.decision.verdict is Verdict.APPROVE


def test_an_exhausted_attempt_budget_leaves_nothing_to_retry(scorer, rates) -> None:
    """Four attempts is the whole of NPCI's allowance. The fifth is not a low-value
    action, it is not an action."""
    plan = decide(state(attempts_used=4), scorer=scorer, rates=rates)
    assert plan.chosen.kind is ActionKind.WRITE_OFF
    retries = [c for c in plan.candidates if c.kind is ActionKind.RETRY]
    assert retries and all(c.decision.verdict is Verdict.DENY for c in retries)
    assert all(c.decision.stop_reason == "npci_1_plus_3_cap_exhausted" for c in retries)


def test_a_revoked_mandate_is_never_retried(scorer, rates) -> None:
    """``BD_hard`` means the authorisation no longer exists. A retry against it spends
    one of four legal attempts on nothing at all."""
    plan = decide(state(root_cause=RootCause.BD_HARD), scorer=scorer, rates=rates)
    assert plan.chosen.kind is not ActionKind.RETRY
    retries = [c for c in plan.candidates if c.kind is ActionKind.RETRY]
    assert all(c.decision.verdict is Verdict.DENY for c in retries)


def test_an_afa_breach_escalates_and_is_not_scored_against_anything(scorer, rates) -> None:
    """A ₹40,000 SaaS debit needs a human, and the fact that retrying it would have the
    highest expected value in the batch is not a consideration.

    This is the test that would fail if escalation were ever folded into the expected
    value comparison — which is precisely the change that would make the model an
    argument against the law rather than a chooser among what the law permits.
    """
    big = replace(INVOICE, amount_paise=paise(40_000))
    plan = decide(
        state(invoice=big, subscription=replace(SUBSCRIPTION, amount_paise=paise(40_000))),
        scorer=scorer,
        rates=rates,
    )
    assert plan.chosen.kind is ActionKind.ESCALATE
    assert plan.chosen.decision.verdict is Verdict.ESCALATE_HUMAN
    assert plan.chosen.expected_value_paise == 0.0


def test_a_denied_candidate_is_kept_in_the_audit_set(scorer, rates) -> None:
    """``decisions.candidate_set`` has to answer "what else did it consider".

    An audit trail that records only approved options cannot tell a policy that chose
    well from one that had no other choice, and the difference is the whole question a
    reviewer is asking.
    """
    plan = decide(state(attempts_used=4), scorer=scorer, rates=rates)
    denied = [c for c in plan.candidates if c.decision.verdict is Verdict.DENY]
    assert denied
    assert all(c.to_dict()["stop_reason"] for c in denied)


# ------------------------------------------------- doing nothing is a real option


def test_an_invoice_worth_less_than_the_attempt_is_written_off(scorer, rates) -> None:
    """₹3 of margin against a 300-paise presentment cost. No probability makes that
    worth doing, and a policy measured on rupees recovered would do it anyway."""
    tiny = replace(INVOICE, amount_paise=paise(10))
    plan = decide(
        state(invoice=tiny, subscription=replace(SUBSCRIPTION, amount_paise=paise(10))),
        scorer=scorer,
        rates=rates,
    )
    assert plan.chosen.kind is ActionKind.WRITE_OFF


def test_write_off_is_always_available(scorer, rates) -> None:
    """Including when every other action is denied. An autonomous system with no legal
    move is an autonomous system that will find an illegal one."""
    plan = decide(state(attempts_used=4, root_cause=RootCause.BD_HARD), scorer=scorer, rates=rates)
    assert plan.chosen.kind is ActionKind.WRITE_OFF
    assert plan.chosen.expected_value_paise == 0.0


# ------------------------------------------------- the lookahead is a lookahead


def test_the_remaining_budget_is_priced_into_every_retry(scorer, rates) -> None:
    """The same invoice is worth more with three attempts left than with one.

    This is the property that separates the backward induction from a greedy argmax: the
    greedy value of a retry does not depend on what is left afterwards, so under a greedy
    rule these two numbers would be equal.
    """
    early = decide(state(attempts_used=1), scorer=scorer, rates=rates)
    late = decide(state(attempts_used=3), scorer=scorer, rates=rates)

    def best_retry(plan) -> float:
        return max(c.expected_value_paise for c in plan.candidates if c.kind is ActionKind.RETRY)

    assert best_retry(early) > best_retry(late)


def test_the_search_actually_expands_a_tree(scorer, rates) -> None:
    """A depth-1 search would expand one node per top-level candidate. Anything less than
    that many is a lookahead that quietly stopped looking ahead."""
    plan = decide(state(attempts_used=1), scorer=scorer, rates=rates)
    assert plan.nodes_expanded > len(plan.candidates)


def test_the_node_budget_bounds_the_search(scorer, rates) -> None:
    """And truncates towards write-off, which can only understate a branch. A truncation
    that could overstate one would make the cost bound a source of bad decisions."""
    params = replace(DEFAULT_POLICY, max_nodes=1)
    plan = decide(state(), scorer=scorer, rates=rates, params=params)
    assert plan.nodes_expanded <= 1
    full = decide(state(), scorer=scorer, rates=rates)
    truncated = max(c.expected_value_paise for c in plan.candidates if c.kind is ActionKind.RETRY)
    complete = max(c.expected_value_paise for c in full.candidates if c.kind is ActionKind.RETRY)
    assert truncated <= complete


def test_the_same_state_always_produces_the_same_plan(scorer, rates) -> None:
    """The decision has to replay from the audit row, months later, on another machine."""
    first = decide(state(), scorer=scorer, rates=rates)
    second = decide(state(), scorer=scorer, rates=rates)
    assert first.to_dict() == second.to_dict()


# ------------------------------------------------- the nudge is the policy's own belief


def test_a_nudge_the_customer_may_not_receive_is_never_chosen(scorer, rates) -> None:
    """And the refusal is recorded with the reason, because "why was this account never
    contacted?" is a question the audit trail has to be able to answer."""
    withdrawn = replace(CUSTOMER, consent_status="withdrawn")
    plan = decide(state(customer=withdrawn), scorer=scorer, rates=rates)
    nudges = [c for c in plan.candidates if c.kind is ActionKind.NUDGE]
    assert nudges and all(c.decision.verdict is Verdict.DENY for c in nudges)
    assert nudges[0].decision.stop_reason == "consent_withdrawn"
    assert plan.chosen.kind is not ActionKind.NUDGE


def test_the_policy_does_not_nudge_twice(scorer, rates) -> None:
    """Under the policy's own belief a second message inside the window buys nothing, so
    proposing one would be spending money to learn that."""
    plan = decide(state(nudged_at=NOW - timedelta(hours=6)), scorer=scorer, rates=rates)
    assert not [c for c in plan.candidates if c.kind is ActionKind.NUDGE]


def test_the_believed_nudge_effect_expires(scorer, rates) -> None:
    """Shape, not size. The size is an assumption and is reported across a range."""
    search = policy._Search(
        state(), scorer=scorer, rates=rates, params=DEFAULT_POLICY, costs=policy.DEFAULT_COSTS
    )
    inside = search.probability(
        attempts_used=1,
        at=NOW,
        prior=PRIOR,
        nudged_at=NOW - timedelta(hours=DEFAULT_POLICY.assumed_nudge_effect_hours),
    )
    outside = search.probability(
        attempts_used=1,
        at=NOW,
        prior=PRIOR,
        nudged_at=NOW - timedelta(hours=DEFAULT_POLICY.assumed_nudge_effect_hours + 1),
    )
    quiet = search.probability(attempts_used=1, at=NOW, prior=PRIOR, nudged_at=None)
    assert inside > quiet
    assert outside == quiet


def test_a_message_sent_after_the_debit_cannot_have_funded_it(scorer, rates) -> None:
    search = policy._Search(
        state(), scorer=scorer, rates=rates, params=DEFAULT_POLICY, costs=policy.DEFAULT_COSTS
    )
    quiet = search.probability(attempts_used=1, at=NOW, prior=PRIOR, nudged_at=None)
    simultaneous = search.probability(attempts_used=1, at=NOW, prior=PRIOR, nudged_at=NOW)
    assert simultaneous == quiet


def test_the_policy_belief_is_not_the_world_constant() -> None:
    """Stated as a test so it cannot drift.

    If these two were ever set from one another, arm D's advantage would be an artifact
    of having been handed the answer, and the sensitivity table in
    ``docs/EVALUATION.md`` would be measuring nothing.
    """
    from sim.world import DEFAULT_PARAMS

    assert (
        DEFAULT_POLICY.assumed_nudge_failure_multiplier != DEFAULT_PARAMS.nudge_balance_multiplier
    )
    assert DEFAULT_POLICY.assumed_nudge_effect_hours != DEFAULT_PARAMS.nudge_effect_hours
